# Generated by Django 4.2.1 on 2025-08-08 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('position', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Commission rate as decimal (e.g., 0.05 for 5%)', max_digits=5)),
                ('monthly_sales_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_calls_target', models.IntegerField(default=0)),
                ('monthly_meetings_target', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deals_closed', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage', max_digits=5)),
                ('calls_made', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('meetings_held', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('new_customers_acquired', models.IntegerField(default=0)),
                ('customer_satisfaction_score', models.DecimalField(blank=True, decimal_places=1, help_text='Out of 5.0', max_digits=3, null=True)),
                ('customer_retention_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage', max_digits=5)),
                ('average_response_time_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('service_completion_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage', max_digits=5)),
                ('sales_target_achievement', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage', max_digits=5)),
                ('activity_target_achievement', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage', max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated overall performance score', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='employees.employee')),
            ],
            options={
                'ordering': ['-month', 'employee__user__first_name'],
                'indexes': [models.Index(fields=['employee', 'month'], name='employees_e_employe_62938f_idx'), models.Index(fields=['month'], name='employees_e_month_f8ba2a_idx')],
                'unique_together': {('employee', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('sales', 'Sales'), ('activity', 'Activity'), ('customer_satisfaction', 'Customer Satisfaction'), ('productivity', 'Productivity'), ('personal_development', 'Personal Development')], max_length=30)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(help_text="e.g., 'dollars', 'calls', 'customers', 'hours'", max_length=50)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='employees_e_employe_f0181a_idx'), models.Index(fields=['target_date'], name='employees_e_target__0b2b87_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_status'], name='employees_e_employm_b2a249_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employees_e_departm_99b42d_idx'),
        ),
    ]
