# Generated by Django 4.2.1 on 2025-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeekpi',
            name='calculated_at',
            field=models.DateTimeField(blank=True, help_text='When KPIs were last calculated', null=True),
        ),
    ]
