# Generated by Django 4.2.1 on 2025-08-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeekpi_calculated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeekpi',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_kpis', to='employees.employee'),
        ),
    ]
